spring:
  application:
    name: spring-resilienc4j

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        registerHealthIndicator: true


management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      showDetails: always
    web:
      exposure:
        include: "*"
      expose: "*"
    metrics:
      enabled: true
  metrics:
    enable:
      resilience4j:
        circuitbreaker:
          calls: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        slidingWindowSize: 10
#        failureRateThreshold: 50
#        waitDurationInOpenState : 10s
#    instances:
#      myCircut:
#        baseConfig: default

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 5s
#        failureRateThreshold: 5
##      eventConsumerBufferSize: 10
##      recordExceptions:
##        - org.springframework.web.client.HttpServerErrorException
##        - java.util.concurrent.TimeoutException
##        - java.io.IOException
#        ignoreExceptions:
#        - com.example.springresilienc4j.application.exception.IgnoreException
#      instances:
#        myCircuit:
#          baseConfig: default
